apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-frontend-ingress
  namespace: taskflow
spec:
  ingressClassName: nginx
  rules:
  - host: taskflow.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taskflow-frontend-service
            port:
              number: 80
